#   Plugin Makefile
#
#   Copyright (c) 2007-2008 Alberto Dainotti, Walter de Donato, Antonio Pescape, Alessio Botta
#   Email: alberto@unina.it, walter.dedonato@unina.it, pescape@unina.it, a.botta@unina.it
#   DIS - Dipartimento di Informatica e Sistemistica (Computer Science Department)
#   University of Naples Federico II
#   All rights reserved.

#---------------------
include ../options.mk
#---------------------

# Specify here additional OBJECTS needed by this plugin 
OBJECTS	+=

# Specify here additional linker flags needed by this plugin
LDFLAGS +=

# Specify here static libraries needed by this plugin
LIBS	:=

# Specify here files and folders to be copied to plugin destination folder togheter with the plugin.
# Each folder is recursively processed skipping hidden files/folders. 
# Each file will be copied in update mode (overwrite only if newer).
COPY	:= Application_ports_Master.txt

#---------------------
include ../rules.mk
#---------------------

# Specify here custom rules if needed

# EOF
